FROM python:3.7 AS base

WORKDIR /usr/src/app

# ---- Dependencies ----
FROM base AS dependencies  
COPY ./requirements.txt ./
# install app dependencies
RUN pip install -r requirements.txt

# ---- Copy Files/Build ----
FROM dependencies AS build  
WORKDIR /usr/src/app
COPY . /usr/src/app

# --- Release with Alpine ----
FROM python:3.7-alpine AS release  
# Create app directory
WORKDIR /usr/src/app

COPY --from=dependencies /usr/src/app/requirements.txt ./
COPY --from=dependencies /root/.cache /root/.cache

# Install app dependencies
RUN pip install -r requirements.txt
COPY --from=build /usr/src/app/ ./
EXPOSE 5000
#CMD ["python", "-u", "async_rmq.py"]