FROM python:3.7-slim AS builder

RUN apt-get update && \ 
    apt-get upgrade -y && \
    apt-get install -y git gcc

WORKDIR /usr/src/app
COPY . .

RUN pip install -r requirements.txt


FROM python:3.7-slim
COPY --from=builder /usr/src/app /usr/src/app/

EXPOSE 5000
CMD ["python", "-u", "async_rmq.py"]
